const powerGenerators = [
  {
    id: 1,
    dictname: 'Дизельный, Отечественный, До капитального ремонта, Группа - А',
    month: 3,
    pollutantvalues: [
      {
        code: '0337',
        name: 'Углерода оксид',
        gseccoef: 7.2,
        tyearcoef: 30,
      },
      {
        code: '0301',
        name: 'Азота диоксид',
        gseccoef: 8.24,
        tyearcoef: 34,
      },
      {
        code: '0304',
        name: 'Азота оксид',
        gseccoef: 1.34,
        tyearcoef: 5.59,
      },
      {
        code: '2754',
        name: 'Углеводороды пред. С12-С19',
        gseccoef: 3.6,
        tyearcoef: 4.29,
      },
      {
        code: '0328',
        name: 'Сажа',
        gseccoef: 0.7,
        tyearcoef: 0.86,
      },
      {
        code: '0330',
        name: 'Серы диоксид',
        gseccoef: 1.1,
        tyearcoef: 5.5,
      },
      {
        code: '1325',
        name: 'Формальдегид',
        gseccoef: 0.15,
        tyearcoef: 0.17,
      },
      {
        code: '0703',
        name: 'Бенз(а)пирен',
        gseccoef: 0.0000130,
        tyearcoef: 0.0000157142857142857,
      },
    ],
  },
  {
    id: 2,
    dictname: 'Дизельный, Отечественный, До капитального ремонта, Группа - Б',
    month: 3,
    pollutantvalues: [
      {
        code: '0301',
        name: 'Азота диоксид',
        gseccoef: 0.004,
        tyearcoef: 0.00043,
      },
      {
        code: '0304',
        name: 'Азота оксид',
        gseccoef: 2,
        tyearcoef: 0.4,
      },
      {
        code: '0328',
        name: 'Углерод черный (Сажа)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0330',
        name: 'Серы диоксид (Ангидрид сернистый)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0337',
        name: 'Углерода оксид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0703',
        name: 'Бенз/а/пирен (3-4-бензпирен)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '1325',
        name: 'Формальдегид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '2754',
        name: 'Углеводороды предельные С12-С19 (в пересчете на С)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
    ],
  },
  {
    id: 4,
    dictname: 'Дизельный, Отечественный, До капитального ремонта, Группа - В',
    month: 3,
    pollutantvalues: [
      {
        code: '0301',
        name: 'Азота диоксид',
        gseccoef: 0.004,
        tyearcoef: 0.00043,
      },
      {
        code: '0304',
        name: 'Азота оксид',
        gseccoef: 2,
        tyearcoef: 0.4,
      },
      {
        code: '0328',
        name: 'Углерод черный (Сажа)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0330',
        name: 'Серы диоксид (Ангидрид сернистый)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0337',
        name: 'Углерода оксид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0703',
        name: 'Бенз/а/пирен (3-4-бензпирен)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '1325',
        name: 'Формальдегид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '2754',
        name: 'Углеводороды предельные С12-С19 (в пересчете на С)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
    ],
  },
  {
    id: 5,
    dictname: 'Дизельный, Отечественный, До капитального ремонта, Группа - Г',
    month: 3,
    pollutantvalues: [
      {
        code: '0301',
        name: 'Азота диоксид',
        gseccoef: 8.24,
        tyearcoef: 0.00043,
      },
      {
        code: '0304',
        name: 'Азота оксид',
        gseccoef: 1.34,
        tyearcoef: 0.4,
      },
      {
        code: '0328',
        name: 'Углерод черный (Сажа)',
        gseccoef: 0.6,
        tyearcoef: 0.32,
      },
      {
        code: '0330',
        name: 'Серы диоксид (Ангидрид сернистый)',
        gseccoef: 1.2,
        tyearcoef: 0.2,
      },
      {
        code: '0337',
        name: 'Углерода оксид',
        gseccoef: 7.2,
        tyearcoef: 0.32,
      },
      {
        code: '0703',
        name: 'Бенз/а/пирен (3-4-бензпирен)',
        gseccoef: 0.000013,
        tyearcoef: 0.32,
      },
      {
        code: '1325',
        name: 'Формальдегид',
        gseccoef: 0.15,
        tyearcoef: 0.32,
      },
      {
        code: '2754',
        name: 'Углеводороды предельные С12-С19 (в пересчете на С)',
        gseccoef: 3.6,
        tyearcoef: 0.32,
      },
    ],
  },
  {
    id: 6,
    dictname: 'Дизельный, Отечественный, После капитального ремонта, Группа - А',
    month: 6,
    pollutantvalues: [
      {
        code: '0301',
        name: 'Азота диоксид',
        gseccoef: 0.004,
        tyearcoef: 0.00043,
      },
      {
        code: '0304',
        name: 'Азота оксид',
        gseccoef: 2,
        tyearcoef: 0.4,
      },
      {
        code: '0328',
        name: 'Углерод черный (Сажа)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0330',
        name: 'Серы диоксид (Ангидрид сернистый)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0337',
        name: 'Углерода оксид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0703',
        name: 'Бенз/а/пирен (3-4-бензпирен)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '1325',
        name: 'Формальдегид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '2754',
        name: 'Углеводороды предельные С12-С19 (в пересчете на С)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
    ],
  },
  {
    id: 7,
    dictname: 'Дизельный, Отечественный, После капитального ремонта, Группа - Б',
    month: 6,
    pollutantvalues: [
      {
        code: '0301',
        name: 'Азота диоксид',
        gseccoef: 0.004,
        tyearcoef: 0.00043,
      },
      {
        code: '0304',
        name: 'Азота оксид',
        gseccoef: 2,
        tyearcoef: 0.4,
      },
      {
        code: '0328',
        name: 'Углерод черный (Сажа)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0330',
        name: 'Серы диоксид (Ангидрид сернистый)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0337',
        name: 'Углерода оксид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0703',
        name: 'Бенз/а/пирен (3-4-бензпирен)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '1325',
        name: 'Формальдегид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '2754',
        name: 'Углеводороды предельные С12-С19 (в пересчете на С)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
    ],
  },
  {
    id: 8,
    dictname: 'Дизельный, Отечественный, После капитального ремонта, Группа - В',
    month: 6,
    pollutantvalues: [
      {
        code: '0301',
        name: 'Азота диоксид',
        gseccoef: 0.004,
        tyearcoef: 0.00043,
      },
      {
        code: '0304',
        name: 'Азота оксид',
        gseccoef: 2,
        tyearcoef: 0.4,
      },
      {
        code: '0328',
        name: 'Углерод черный (Сажа)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0330',
        name: 'Серы диоксид (Ангидрид сернистый)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0337',
        name: 'Углерода оксид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0703',
        name: 'Бенз/а/пирен (3-4-бензпирен)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '1325',
        name: 'Формальдегид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '2754',
        name: 'Углеводороды предельные С12-С19 (в пересчете на С)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
    ],
  },
  {
    id: 9,
    dictname: 'Дизельный, Отечественный, После капитального ремонта, Группа - Г',
    month: 6,
    pollutantvalues: [
      {
        code: '0301',
        name: 'Азота диоксид',
        gseccoef: 0.004,
        tyearcoef: 0.00043,
      },
      {
        code: '0304',
        name: 'Азота оксид',
        gseccoef: 2,
        tyearcoef: 0.4,
      },
      {
        code: '0328',
        name: 'Углерод черный (Сажа)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0330',
        name: 'Серы диоксид (Ангидрид сернистый)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0337',
        name: 'Углерода оксид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0703',
        name: 'Бенз/а/пирен (3-4-бензпирен)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '1325',
        name: 'Формальдегид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '2754',
        name: 'Углеводороды предельные С12-С19 (в пересчете на С)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
    ],
  },
  {
    id: 10,
    dictname: 'Дизельный, Зарубежный, До капитального ремонта, Группа - А',
    month: 34,
    pollutantvalues: [
      {
        code: '0301',
        name: 'Азота диоксид',
        gseccoef: 0.004,
        tyearcoef: 0.00043,
      },
      {
        code: '0304',
        name: 'Азота оксид',
        gseccoef: 2,
        tyearcoef: 0.4,
      },
      {
        code: '0328',
        name: 'Углерод черный (Сажа)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0330',
        name: 'Серы диоксид (Ангидрид сернистый)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0337',
        name: 'Углерода оксид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0703',
        name: 'Бенз/а/пирен (3-4-бензпирен)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '1325',
        name: 'Формальдегид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '2754',
        name: 'Углеводороды предельные С12-С19 (в пересчете на С)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
    ],
  },
  {
    id: 11,
    dictname: 'Дизельный, Зарубежный, До капитального ремонта, Группа - Б',
    month: 45,
    pollutantvalues: [
      {
        code: '0301',
        name: 'Азота диоксид',
        gseccoef: 0.004,
        tyearcoef: 0.00043,
      },
      {
        code: '0304',
        name: 'Азота оксид',
        gseccoef: 2,
        tyearcoef: 0.4,
      },
      {
        code: '0328',
        name: 'Углерод черный (Сажа)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0330',
        name: 'Серы диоксид (Ангидрид сернистый)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0337',
        name: 'Углерода оксид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0703',
        name: 'Бенз/а/пирен (3-4-бензпирен)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '1325',
        name: 'Формальдегид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '2754',
        name: 'Углеводороды предельные С12-С19 (в пересчете на С)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
    ],
  },
  {
    id: 12,
    dictname: 'Дизельный, Зарубежный, До капитального ремонта, Группа - В',
    month: 45,
    pollutantvalues: [
      {
        code: '0301',
        name: 'Азота диоксид',
        gseccoef: 0.004,
        tyearcoef: 0.00043,
      },
      {
        code: '0304',
        name: 'Азота оксид',
        gseccoef: 2,
        tyearcoef: 0.4,
      },
      {
        code: '0328',
        name: 'Углерод черный (Сажа)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0330',
        name: 'Серы диоксид (Ангидрид сернистый)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0337',
        name: 'Углерода оксид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0703',
        name: 'Бенз/а/пирен (3-4-бензпирен)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '1325',
        name: 'Формальдегид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '2754',
        name: 'Углеводороды предельные С12-С19 (в пересчете на С)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
    ],
  },
  {
    id: 13,
    dictname: 'Дизельный, Зарубежный, До капитального ремонта, Группа - Г',
    month: 45,
    pollutantvalues: [
      {
        code: '0301',
        name: 'Азота диоксид',
        gseccoef: 0.004,
        tyearcoef: 0.00043,
      },
      {
        code: '0304',
        name: 'Азота оксид',
        gseccoef: 2,
        tyearcoef: 0.4,
      },
      {
        code: '0328',
        name: 'Углерод черный (Сажа)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0330',
        name: 'Серы диоксид (Ангидрид сернистый)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0337',
        name: 'Углерода оксид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0703',
        name: 'Бенз/а/пирен (3-4-бензпирен)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '1325',
        name: 'Формальдегид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '2754',
        name: 'Углеводороды предельные С12-С19 (в пересчете на С)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
    ],
  },
  {
    id: 14,
    dictname: 'Дизельный, Зарубежный, После капитального ремонта, Группа - А',
    month: 34,
    pollutantvalues: [
      {
        code: '0301',
        name: 'Азота диоксид',
        gseccoef: 0.004,
        tyearcoef: 0.00043,
      },
      {
        code: '0304',
        name: 'Азота оксид',
        gseccoef: 2,
        tyearcoef: 0.4,
      },
      {
        code: '0328',
        name: 'Углерод черный (Сажа)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0330',
        name: 'Серы диоксид (Ангидрид сернистый)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0337',
        name: 'Углерода оксид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0703',
        name: 'Бенз/а/пирен (3-4-бензпирен)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '1325',
        name: 'Формальдегид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '2754',
        name: 'Углеводороды предельные С12-С19 (в пересчете на С)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
    ],
  },
  {
    id: 15,
    dictname: 'Дизельный, Зарубежный, После капитального ремонта, Группа - Б',
    month: 45,
    pollutantvalues: [
      {
        code: '0301',
        name: 'Азота диоксид',
        gseccoef: 0.004,
        tyearcoef: 0.00043,
      },
      {
        code: '0304',
        name: 'Азота оксид',
        gseccoef: 2,
        tyearcoef: 0.4,
      },
      {
        code: '0328',
        name: 'Углерод черный (Сажа)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0330',
        name: 'Серы диоксид (Ангидрид сернистый)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0337',
        name: 'Углерода оксид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0703',
        name: 'Бенз/а/пирен (3-4-бензпирен)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '1325',
        name: 'Формальдегид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '2754',
        name: 'Углеводороды предельные С12-С19 (в пересчете на С)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
    ],
  },
  {
    id: 16,
    dictname: 'Дизельный, Зарубежный, После капитального ремонта, Группа - В',
    month: 45,
    pollutantvalues: [
      {
        code: '0301',
        name: 'Азота диоксид',
        gseccoef: 0.004,
        tyearcoef: 0.00043,
      },
      {
        code: '0304',
        name: 'Азота оксид',
        gseccoef: 2,
        tyearcoef: 0.4,
      },
      {
        code: '0328',
        name: 'Углерод черный (Сажа)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0330',
        name: 'Серы диоксид (Ангидрид сернистый)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0337',
        name: 'Углерода оксид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0703',
        name: 'Бенз/а/пирен (3-4-бензпирен)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '1325',
        name: 'Формальдегид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '2754',
        name: 'Углеводороды предельные С12-С19 (в пересчете на С)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
    ],
  },
  {
    id: 17,
    dictname: 'Дизельный, Зарубежный, После капитального ремонта, Группа - Г',
    month: 45,
    pollutantvalues: [
      {
        code: '0301',
        name: 'Азота диоксид',
        gseccoef: 0.004,
        tyearcoef: 0.00043,
      },
      {
        code: '0304',
        name: 'Азота оксид',
        gseccoef: 2,
        tyearcoef: 0.4,
      },
      {
        code: '0328',
        name: 'Углерод черный (Сажа)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0330',
        name: 'Серы диоксид (Ангидрид сернистый)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0337',
        name: 'Углерода оксид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '0703',
        name: 'Бенз/а/пирен (3-4-бензпирен)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '1325',
        name: 'Формальдегид',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
      {
        code: '2754',
        name: 'Углеводороды предельные С12-С19 (в пересчете на С)',
        gseccoef: 3,
        tyearcoef: 0.32,
      },
    ],
  },
];

const stitchedMultiplier = 1.25;
const maxArea = 805;

module.exports = {
  powerGenerators,
  stitchedMultiplier,
  maxArea,
};
